### ISSUE TITLE
does this hash table need deallocate

### ISSUE THREAD

**Issue by bryanhan1001** [pdebuyl/fortran_hash_table#1]
hello, 
does this hash table need deallocate if the program run forever, how can i deal with it?
thanks

**Comment by pdebuyl** [comment]
Hello,

The memory footprint, if used for a configuration file for instance, is not big. But indeed, the memory is never freed in the code here.

There are two options:

1. As only "allocatable" arrays are used, if you don't have a `dictionary_m` variable in the main program but in a subroutine it should be cleaned automatically.
2. Add code to deallocate all `buckets(*)%entries` and then `buckets` explicitly. I can do that if you are interested.

**Comment by bryanhan1001** [comment]
thansk for your reply!

In my business, it needs to be remained in memory. I just want to learn about the code. And in my mind of clang, there will be a deallocate operation. I will be appreciate if you can make it when you are available!

**Comment by pdebuyl** [comment]
Hello @bryanhan1001 as I mentioned, if you keep the object in scope it will remain in memory. Could you provide a skeleton example of what you try to achieve?

**Comment by bryanhan1001** [comment]
sorry，I am new to fortran. so i want to know how to deallocate the hash map here
